package com.thehub.hb.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class HubStrings(
    // Bottom Navigation
    val tabFeed: String,
    val tabSearch: String,
    val tabCreate: String,
    val tabNotifications: String,
    val tabProfile: String,

    // Settings Screen
    val settingsTitle: String,
    val accountSection: String,
    val editProfile: String,
    val editProfileSubtitle: String,
    val changePassword: String,
    val changePasswordSubtitle: String,
    val privacySection: String,
    val blockedUsers: String,
    val blockedUsersSubtitle: String,
    val appearanceAndLanguageSection: String,
    val themeModeTitle: String,
    val appLanguageTitle: String,
    val notificationsSection: String,
    val notifLikes: String,
    val notifLikesSubtitle: String,
    val notifComments: String,
    val notifCommentsSubtitle: String,
    val notifFollows: String,
    val notifFollowsSubtitle: String,
    val notifMessages: String,
    val notifMessagesSubtitle: String,
    val aboutSection: String,
    val termsTitle: String,
    val termsSubtitle: String,
    val appVersionTitle: String,
    val checkForUpdatesTitle: String,
    val checkForUpdatesSubtitle: String,
    val signOutTitle: String,
    val deleteAccountTitle: String,
    val deleteAccountSubtitle: String,

    // Dialogs & Confirmations
    val dialogThemeTitle: String,
    val dialogLanguageTitle: String,
    val dialogSignOutTitle: String,
    val dialogSignOutMessage: String,
    val dialogDeleteAccountTitle: String,
    val dialogDeleteAccountMessage: String,
    val dialogConfirm: String,
    val dialogCancel: String,
    val dialogClose: String,
    val deletingAccount: String,

    // Feed & Post
    val forYou: String,
    val following: String,
    val friendsOnly: String,
    val noPostsYet: String,
    val pullToRefresh: String,
    val share: String,
    val repost: String,
    val comments: String,
    val likes: String,
    val writeComment: String,
    val send: String,
    val deletePost: String,
    val reportPost: String,
    val bookmarkAdded: String,
    val bookmarkRemoved: String,

    // Create Post
    val publish: String,
    val whatOnYourMind: String,
    val addPhoto: String,
    val publishing: String,

    // Profile
    val followers: String,
    val followingCount: String,
    val postsCount: String,
    val follow: String,
    val unfollow: String,
    val message: String,
    val editBio: String,
    val noBio: String,

    // Search
    val searchPlaceholder: String,
    val searchUsers: String,
    val searchHashtags: String,
    val trendingTopics: String,
    val noResultsFound: String,

    // Notifications
    val notificationsTitle: String,
    val noNotifications: String,
    val likedYourPost: String,
    val commentedOnYourPost: String,
    val startedFollowingYou: String,

    // Messaging
    val messagesTitle: String,
    val typeMessage: String,
    val noConversations: String,

    // Updates
    val updateAvailable: String,
    val updateWhatsNew: String,
    val updateDownload: String,
    val updateDownloading: String,
    val updateInstall: String,
    val updateLater: String,
    val updateChecking: String,
    val updateUpToDate: String,

    // Errors & Auth
    val accountDeletedError: String,
    val connectionError: String,
    val emailPlaceholder: String,
    val passwordPlaceholder: String,
    val loginButton: String,
    val signUpButton: String
)

val FrHubStrings = HubStrings(
    tabFeed = "Feed",
    tabSearch = "Recherche",
    tabCreate = "Publier",
    tabNotifications = "Notifs",
    tabProfile = "Profil",

    settingsTitle = "Paramètres",
    accountSection = "Compte",
    editProfile = "Modifier le profil",
    editProfileSubtitle = "Nom, bio, photo et date de naissance",
    changePassword = "Changer le mot de passe",
    changePasswordSubtitle = "Mettre à jour votre mot de passe",
    privacySection = "Confidentialité",
    blockedUsers = "Utilisateurs bloqués",
    blockedUsersSubtitle = "Gérer les profils que vous avez bloqués",
    appearanceAndLanguageSection = "Apparence & Langue",
    themeModeTitle = "Mode d'affichage (Thème)",
    appLanguageTitle = "Langue de l'application",
    notificationsSection = "Notifications",
    notifLikes = "Mentions J'aime",
    notifLikesSubtitle = "Lorsqu'un utilisateur aime vos publications",
    notifComments = "Commentaires",
    notifCommentsSubtitle = "Lorsqu'un commentaire est déposé sur votre post",
    notifFollows = "Nouveaux abonnés",
    notifFollowsSubtitle = "Lorsqu'un utilisateur commence à vous suivre",
    notifMessages = "Messages directs",
    notifMessagesSubtitle = "À la réception d'un nouveau message privé",
    aboutSection = "À propos",
    termsTitle = "Conditions d'utilisation & Confidentialité",
    termsSubtitle = "Consulter les règles d'utilisation",
    appVersionTitle = "Version de l'application",
    checkForUpdatesTitle = "Vérifier les mises à jour",
    checkForUpdatesSubtitle = "Rechercher la dernière version GitHub",
    signOutTitle = "Se déconnecter",
    deleteAccountTitle = "Supprimer mon compte",
    deleteAccountSubtitle = "Cette action est irréversible",

    dialogThemeTitle = "Choisir le thème",
    dialogLanguageTitle = "Langue de l'application",
    dialogSignOutTitle = "Déconnexion",
    dialogSignOutMessage = "Êtes-vous sûr de vouloir vous déconnecter de The Hub ?",
    dialogDeleteAccountTitle = "Supprimer définitivement le compte ?",
    dialogDeleteAccountMessage = "Toutes vos données, publications, abonnements et messages seront définitivement supprimés.",
    dialogConfirm = "Confirmer",
    dialogCancel = "Annuler",
    dialogClose = "Fermer",
    deletingAccount = "Suppression en cours...",

    forYou = "Pour vous",
    following = "Abonnements",
    friendsOnly = "Amis",
    noPostsYet = "Aucune publication pour le moment",
    pullToRefresh = "Tirer pour actualiser",
    share = "Partager",
    repost = "Republier",
    comments = "Commentaires",
    likes = "J'aime",
    writeComment = "Écrire un commentaire...",
    send = "Envoyer",
    deletePost = "Supprimer la publication",
    reportPost = "Signaler",
    bookmarkAdded = "Ajouté aux favoris",
    bookmarkRemoved = "Retiré des favoris",

    publish = "Publier",
    whatOnYourMind = "Quoi de neuf ?",
    addPhoto = "Ajouter une photo",
    publishing = "Publication...",

    followers = "Abonnés",
    followingCount = "Abonnements",
    postsCount = "Publications",
    follow = "Suivre",
    unfollow = "Ne plus suivre",
    message = "Message",
    editBio = "Modifier la bio",
    noBio = "Aucune bio renseignée",

    searchPlaceholder = "Rechercher sur The Hub...",
    searchUsers = "Comptes",
    searchHashtags = "Hashtags",
    trendingTopics = "Tendances",
    noResultsFound = "Aucun résultat trouvé",

    notificationsTitle = "Notifications",
    noNotifications = "Aucune notification",
    likedYourPost = "a aimé votre publication",
    commentedOnYourPost = "a commenté votre publication",
    startedFollowingYou = "a commencé à vous suivre",

    messagesTitle = "Messages",
    typeMessage = "Votre message...",
    noConversations = "Aucune conversation",

    updateAvailable = "Mise à jour disponible",
    updateWhatsNew = "Modifications apportées",
    updateDownload = "Télécharger",
    updateDownloading = "Téléchargement...",
    updateInstall = "Installer",
    updateLater = "Plus tard",
    updateChecking = "Vérification de la mise à jour...",
    updateUpToDate = "The Hub est à jour !",

    accountDeletedError = "Ce compte a été supprimé.",
    connectionError = "Erreur de connexion. Vérifiez votre réseau.",
    emailPlaceholder = "Adresse email",
    passwordPlaceholder = "Mot de passe",
    loginButton = "Se connecter",
    signUpButton = "S'inscrire"
)

val EnHubStrings = HubStrings(
    tabFeed = "Feed",
    tabSearch = "Search",
    tabCreate = "Post",
    tabNotifications = "Alerts",
    tabProfile = "Profile",

    settingsTitle = "Settings",
    accountSection = "Account",
    editProfile = "Edit profile",
    editProfileSubtitle = "Name, bio, photo and birthdate",
    changePassword = "Change password",
    changePasswordSubtitle = "Update your account password",
    privacySection = "Privacy",
    blockedUsers = "Blocked users",
    blockedUsersSubtitle = "Manage accounts you have blocked",
    appearanceAndLanguageSection = "Appearance & Language",
    themeModeTitle = "Display mode (Theme)",
    appLanguageTitle = "App language",
    notificationsSection = "Notifications",
    notifLikes = "Likes",
    notifLikesSubtitle = "When someone likes your posts",
    notifComments = "Comments",
    notifCommentsSubtitle = "When someone comments on your post",
    notifFollows = "New followers",
    notifFollowsSubtitle = "When someone starts following you",
    notifMessages = "Direct messages",
    notifMessagesSubtitle = "When you receive a new private message",
    aboutSection = "About",
    termsTitle = "Terms of Service & Privacy",
    termsSubtitle = "Review our guidelines and rules",
    appVersionTitle = "App version",
    checkForUpdatesTitle = "Check for updates",
    checkForUpdatesSubtitle = "Check the latest GitHub release",
    signOutTitle = "Sign out",
    deleteAccountTitle = "Delete my account",
    deleteAccountSubtitle = "This action cannot be undone",

    dialogThemeTitle = "Choose theme",
    dialogLanguageTitle = "App language",
    dialogSignOutTitle = "Sign out",
    dialogSignOutMessage = "Are you sure you want to sign out of The Hub?",
    dialogDeleteAccountTitle = "Permanently delete account?",
    dialogDeleteAccountMessage = "All your data, posts, followers, and messages will be permanently removed.",
    dialogConfirm = "Confirm",
    dialogCancel = "Cancel",
    dialogClose = "Close",
    deletingAccount = "Deleting account...",

    forYou = "For You",
    following = "Following",
    friendsOnly = "Friends",
    noPostsYet = "No posts yet",
    pullToRefresh = "Pull to refresh",
    share = "Share",
    repost = "Repost",
    comments = "Comments",
    likes = "Likes",
    writeComment = "Write a comment...",
    send = "Send",
    deletePost = "Delete post",
    reportPost = "Report",
    bookmarkAdded = "Saved to bookmarks",
    bookmarkRemoved = "Removed from bookmarks",

    publish = "Post",
    whatOnYourMind = "What's on your mind?",
    addPhoto = "Add photo",
    publishing = "Posting...",

    followers = "Followers",
    followingCount = "Following",
    postsCount = "Posts",
    follow = "Follow",
    unfollow = "Unfollow",
    message = "Message",
    editBio = "Edit bio",
    noBio = "No bio provided",

    searchPlaceholder = "Search on The Hub...",
    searchUsers = "Accounts",
    searchHashtags = "Hashtags",
    trendingTopics = "Trending",
    noResultsFound = "No results found",

    notificationsTitle = "Notifications",
    noNotifications = "No notifications yet",
    likedYourPost = "liked your post",
    commentedOnYourPost = "commented on your post",
    startedFollowingYou = "started following you",

    messagesTitle = "Messages",
    typeMessage = "Type a message...",
    noConversations = "No conversations yet",

    updateAvailable = "Update Available",
    updateWhatsNew = "What's Changed",
    updateDownload = "Download",
    updateDownloading = "Downloading...",
    updateInstall = "Install",
    updateLater = "Later",
    updateChecking = "Checking for update...",
    updateUpToDate = "The Hub is up to date!",

    accountDeletedError = "This account has been deleted.",
    connectionError = "Connection error. Please check your network.",
    emailPlaceholder = "Email address",
    passwordPlaceholder = "Password",
    loginButton = "Log In",
    signUpButton = "Sign Up"
)

val LocalHubStrings = staticCompositionLocalOf<HubStrings> { FrHubStrings }
