package com.thehub.hb.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class HubStrings(
    // Navigation
    val tabFeed: String,
    val tabSearch: String,
    val tabCreate: String,
    val tabNotifications: String,
    val tabProfile: String,

    // Paramètres
    val settingsTitle: String,
    val accountSection: String,
    val editProfile: String,
    val editProfileSubtitle: String,
    val changePassword: String,
    val changePasswordSubtitle: String,
    val privacySection: String,
    val blockedUsers: String,
    val blockedUsersSubtitle: String,
    val appearanceSection: String,
    val themeModeTitle: String,
    val notificationsSection: String,
    val notifLikes: String,
    val notifLikesSubtitle: String,
    val notifComments: String,
    val notifCommentsSubtitle: String,
    val notifFollows: String,
    val notifFollowsSubtitle: String,
    val notifMessages: String,
    val notifMessagesSubtitle: String,
    val aboutSection: String,
    val termsTitle: String,
    val termsSubtitle: String,
    val appVersionTitle: String,
    val checkForUpdatesTitle: String,
    val checkForUpdatesSubtitle: String,
    val signOutTitle: String,
    val deleteAccountTitle: String,
    val deleteAccountSubtitle: String,

    // Dialogues et confirmations
    val dialogThemeTitle: String,
    val dialogSignOutTitle: String,
    val dialogSignOutMessage: String,
    val dialogDeleteAccountTitle: String,
    val dialogDeleteAccountMessage: String,
    val dialogConfirm: String,
    val dialogCancel: String,
    val dialogClose: String,
    val deletingAccount: String,
    val deleteAccountConfirmationPrompt: String,
    val deleteAccountConfirmationWord: String,

    // Fil et publications
    val forYou: String,
    val following: String,
    val friendsOnly: String,
    val noPostsYet: String,
    val noPostsDescription: String,
    val discoverUsers: String,
    val pullToRefresh: String,
    val share: String,
    val repost: String,
    val comments: String,
    val likes: String,
    val writeComment: String,
    val send: String,
    val deletePost: String,
    val reportPost: String,
    val bookmarkAdded: String,
    val bookmarkRemoved: String,

    // Création de publication
    val publish: String,
    val whatOnYourMind: String,
    val addPhoto: String,
    val publishing: String,

    // Profil
    val followers: String,
    val followingCount: String,
    val postsCount: String,
    val follow: String,
    val unfollow: String,
    val message: String,
    val editBio: String,
    val noBio: String,

    // Recherche
    val searchPlaceholder: String,
    val searchUsers: String,
    val searchHashtags: String,
    val trendingTopics: String,
    val noResultsFound: String,

    // Notifications
    val notificationsTitle: String,
    val noNotifications: String,
    val likedYourPost: String,
    val commentedOnYourPost: String,
    val startedFollowingYou: String,

    // Messagerie
    val messagesTitle: String,
    val typeMessage: String,
    val noConversations: String,

    // Mises à jour
    val updateAvailable: String,
    val updateWhatsNew: String,
    val updateDownload: String,
    val updateDownloading: String,
    val updateInstall: String,
    val updateLater: String,
    val updateChecking: String,
    val updateUpToDate: String,

    // Erreurs et authentification
    val accountDeletedError: String,
    val connectionError: String,
    val emailPlaceholder: String,
    val passwordPlaceholder: String,
    val loginButton: String,
    val signUpButton: String
)

val FrenchHubStrings = HubStrings(
    tabFeed = "Fil",
    tabSearch = "Recherche",
    tabCreate = "Publier",
    tabNotifications = "Notifications",
    tabProfile = "Profil",

    settingsTitle = "Paramètres",
    accountSection = "Compte",
    editProfile = "Modifier le profil",
    editProfileSubtitle = "Nom, bio, photo et date de naissance",
    changePassword = "Changer le mot de passe",
    changePasswordSubtitle = "Mettre à jour votre mot de passe",
    privacySection = "Confidentialité",
    blockedUsers = "Utilisateurs bloqués",
    blockedUsersSubtitle = "Gérer les profils que vous avez bloqués",
    appearanceSection = "Apparence",
    themeModeTitle = "Mode d'affichage (Thème)",
    notificationsSection = "Notifications",
    notifLikes = "Mentions J'aime",
    notifLikesSubtitle = "Lorsqu'un utilisateur aime vos publications",
    notifComments = "Commentaires",
    notifCommentsSubtitle = "Lorsqu'un commentaire est déposé sur votre publication",
    notifFollows = "Nouveaux abonnés",
    notifFollowsSubtitle = "Lorsqu'un utilisateur commence à vous suivre",
    notifMessages = "Messages directs",
    notifMessagesSubtitle = "À la réception d'un nouveau message privé",
    aboutSection = "À propos",
    termsTitle = "Conditions d'utilisation & Confidentialité",
    termsSubtitle = "Consulter les règles d'utilisation",
    appVersionTitle = "Version de l'application",
    checkForUpdatesTitle = "Vérifier les mises à jour",
    checkForUpdatesSubtitle = "Rechercher la dernière version GitHub",
    signOutTitle = "Se déconnecter",
    deleteAccountTitle = "Supprimer mon compte",
    deleteAccountSubtitle = "Cette action est irréversible",

    dialogThemeTitle = "Choisir le thème",
    dialogSignOutTitle = "Déconnexion",
    dialogSignOutMessage = "Êtes-vous sûr de vouloir vous déconnecter de The Hub ?",
    dialogDeleteAccountTitle = "Supprimer définitivement le compte ?",
    dialogDeleteAccountMessage = "Toutes vos données, publications, abonnements et messages seront définitivement supprimés.",
    dialogConfirm = "Confirmer",
    dialogCancel = "Annuler",
    dialogClose = "Fermer",
    deletingAccount = "Suppression en cours...",
    deleteAccountConfirmationPrompt = "Veuillez taper \"SUPPRIMER\" en majuscules pour confirmer la suppression définitive :",
    deleteAccountConfirmationWord = "SUPPRIMER",

    forYou = "Pour vous",
    following = "Abonnements",
    friendsOnly = "Amis",
    noPostsYet = "Votre fil est encore vide",
    noPostsDescription = "Suivez des utilisateurs pour voir leurs publications ici, ou soyez le premier à partager quelque chose avec la communauté !",
    discoverUsers = "Découvrir des utilisateurs",
    pullToRefresh = "Tirer pour actualiser",
    share = "Partager",
    repost = "Republier",
    comments = "Commentaires",
    likes = "J'aime",
    writeComment = "Écrire un commentaire...",
    send = "Envoyer",
    deletePost = "Supprimer la publication",
    reportPost = "Signaler",
    bookmarkAdded = "Ajouté aux favoris",
    bookmarkRemoved = "Retiré des favoris",

    publish = "Publier",
    whatOnYourMind = "Quoi de neuf ?",
    addPhoto = "Ajouter une photo",
    publishing = "Publication...",

    followers = "Abonnés",
    followingCount = "Abonnements",
    postsCount = "Publications",
    follow = "Suivre",
    unfollow = "Ne plus suivre",
    message = "Message",
    editBio = "Modifier la bio",
    noBio = "Aucune bio renseignée",

    searchPlaceholder = "Rechercher sur The Hub...",
    searchUsers = "Comptes",
    searchHashtags = "Hashtags",
    trendingTopics = "Tendances",
    noResultsFound = "Aucun résultat trouvé",

    notificationsTitle = "Notifications",
    noNotifications = "Aucune notification",
    likedYourPost = "a aimé votre publication",
    commentedOnYourPost = "a commenté votre publication",
    startedFollowingYou = "a commencé à vous suivre",

    messagesTitle = "Messages",
    typeMessage = "Votre message...",
    noConversations = "Aucune conversation",

    updateAvailable = "Mise à jour disponible",
    updateWhatsNew = "Modifications apportées",
    updateDownload = "Télécharger",
    updateDownloading = "Téléchargement...",
    updateInstall = "Installer la mise à jour",
    updateLater = "Plus tard",
    updateChecking = "Vérification de la mise à jour...",
    updateUpToDate = "The Hub est à jour !",

    accountDeletedError = "Ce compte a été supprimé.",
    connectionError = "Erreur de connexion. Vérifiez votre réseau.",
    emailPlaceholder = "Adresse email",
    passwordPlaceholder = "Mot de passe",
    loginButton = "Se connecter",
    signUpButton = "S'inscrire"
)

val LocalHubStrings = staticCompositionLocalOf<HubStrings> { FrenchHubStrings }
