package com.thehub.hb.ui.admin

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Article
import androidx.compose.material.icons.filled.Flag
import androidx.compose.material.icons.filled.History
import androidx.compose.material.icons.filled.Home
import androidx.compose.material.icons.filled.Notifications
import androidx.compose.material.icons.filled.People
import androidx.compose.material.icons.filled.Security
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material.icons.filled.Shield
import androidx.compose.material.icons.filled.Search
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import com.google.firebase.Timestamp
import com.thehub.hb.data.repository.AdminAnalyticsV2
import com.thehub.hb.data.repository.AdminAntiSpamConfigV2
import com.thehub.hb.data.repository.AdminControlRepository
import com.thehub.hb.data.repository.AdminEmergencyV2
import com.thehub.hb.data.repository.AdminFeatureFlagV2
import com.thehub.hb.data.repository.AdminUserDetailV2
import com.thehub.hb.data.repository.antiSpamConfig
import com.thehub.hb.data.repository.analyticsV2
import com.thehub.hb.data.repository.assignTicket
import com.thehub.hb.data.repository.emergency
import com.thehub.hb.data.repository.featureFlags
import com.thehub.hb.data.repository.investigation
import com.thehub.hb.data.repository.replyTicket
import com.thehub.hb.data.repository.setAntiSpamConfig
import com.thehub.hb.data.repository.setEmergency
import com.thehub.hb.data.repository.setFeatureFlag
import com.thehub.hb.ui.theme.HubError
import com.thehub.hb.ui.theme.HubOutline
import com.thehub.hb.ui.theme.HubSurface
import com.thehub.hb.ui.theme.HubViolet
import java.util.Date
import kotlinx.coroutines.launch

private enum class AdminV2Section(
    val title: String,
    val description: String,
    val icon: ImageVector